### ISSUE TITLE
Popup opening on ListView scroll

### ISSUE THREAD

**Issue by jaytj95** [RiccardoMoro/LongPressPopup#1]
I register a Popup in ListAdapter (inside getView, I set the Popup target to convertView). When I click or scroll through the list, the popup appears

**Comment by RiccardoMoro** [comment]
I'm looking into this right now, can you please post your getView code?

**Comment by RiccardoMoro** [comment]
Btw, I've checked and sometimes what you said happens,
I'm gonna take a look and solve this, in the meantime, I can assure you that this is working correctly with RecyclerView (which is also the recommend way to make lists by now)
I'll let you know
