### ISSUE TITLE
long prees popup for recyclerview

### ISSUE THREAD

**Issue by MeshkaniMohammad** [RiccardoMoro/LongPressPopup#11]
how to implement longPressPopup for resyclerview?

**Comment by RiccardoMoro** [comment]
The sample app in this repository is using a RecyclerView..

Just check out the [ViewHolder](https://github.com/RiccardoMoro/LongPressPopup/blob/master/app/src/main/java/rm/com/longpresspopupsample/adapters/GalleryViewHolder.java) to see how it's implemented :)
