### ISSUE TITLE
Problem with padding

### ISSUE THREAD

**Issue by mschakulat** [RiccardoMoro/LongPressPopup#3]
Hi..
I have a linearlayout for the popup, with an imageview and two textviews below the imageview. The first time i open a popup, the image seems to have a small top padding. If i open the same popup again, the padding is gone.
Anyone has an idea, what happens there?

**Comment by mschakulat** [comment]
I forgot: I use a recycler view and the popups should open on holding an item..

**Comment by RiccardoMoro** [comment]
Wow sorry, I completely missed this issue...
Are you still having this problem?

**Comment by Jsaiao** [comment]
Hi, i have same problem. U can help me. ;)

**Comment by RiccardoMoro** [comment]
Please post relevant code :)

**Comment by mschakulat** [comment]
I switched to a relativelayout and everything is fine ;)

**Comment by RiccardoMoro** [comment]
Good to know!
Closing, Will take a look at why it was happening anyway, Thank you
