### ISSUE TITLE
Is it possible to keep the popup open after the long click?

### ISSUE THREAD

**Issue by Jsaiao** [RiccardoMoro/LongPressPopup#5]

**Comment by RiccardoMoro** [comment]
setDismissOnLongPressStop(false) in the LongPressPopupBuilder is what you are looking for I guess

**Comment by RiccardoMoro** [comment]
@Jsaiao Let me know if this solved your issue

**Comment by Jsaiao** [comment]
This is amazing work now is possible open popup only click?

**Comment by RiccardoMoro** [comment]
Thank you!
Nope, it's called LongPressPopup ;)
There's a workaround tho, you can set the long press duration to a very small number and it's (almost) like on click but it will appear before the user releases it's finger anyway
.setLongPressDuration(30) // This in the builder

**Comment by Jsaiao** [comment]
This is amazing .setLongPressDuration **(30)** work for me and is beautiful! **_


**_I'm using value 60 as well so I can scroll the page down and up._**


> Thanks for Help!!!

_**
