### ISSUE TITLE
setLongPressDuration? 

### ISSUE THREAD

**Issue by OmarBizreh** [RiccardoMoro/LongPressPopup#7]
Hi, popup keeps on showing even if I increase duration.
Below is my code: 
``` Java
 final LongPressPopup popup = new LongPressPopupBuilder(holder.itemView.getContext())
                .setTarget(holder.itemView.findViewById(R.id.row_product_item_image))
                .setPopupView(v)
                .setLongPressDuration(1250)
                .setDismissOnLongPressStop(true)
                .build();
        v.findViewById(R.id.btnPopUpCancel).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                popup.dismissNow();
            }
        });
        popup.register();
```

I also have setDismissOnLongPressStop, but it doesn't dismiss unless I tap on the cancel button I added to v (Popup view), and the popup still shows when the new activity is on the screen.
LongPressDuration just delays it and doesn't reset if user stops tapping target view

**Comment by OmarBizreh** [comment]
Never mind me, changed setTarget to itemView only instead of a specific view inside my Recycler View holder and now it is working as expected. Thanks.

**Comment by RiccardoMoro** [comment]
Good to know!
I'm sorry that I've completely missed this issue..
My bad

**Comment by OmarBizreh** [comment]
No worries, thank you for your efforts, liking this library so far
